version: '3.1'
services:
  db:
    image: "timescale/timescaledb:latest-pg12"
    container_name: "uptime-db"
    ports:
      - "5432:5432"
    volumes:
      - uptime_db:/var/lib/postgresql/uptime
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: example
volumes:
  uptime_db:
